version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            wget -q -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x hadolint
            sudo mv hadolint /usr/local/bin/
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image to GitHub Packages
          command: |
            IMAGE=ghcr.io/${CIRCLE_PROJECT_USERNAME}/karsajobs-ui:latest
            echo $GHCR_TOKEN | docker login ghcr.io -u $CIRCLE_PROJECT_USERNAME --password-stdin
            docker build -t $IMAGE .
            docker push $IMAGE

workflows:
  version: 2
  frontend_pipeline:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile

